# Generated by Django 3.1.6 on 2021-02-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя лектора'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия лектора'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия студента'),
        ),
    ]
