# Generated by Django 3.1.6 on 2021-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210220_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=100)),
                ('text_message', models.CharField(max_length=200, verbose_name='Текс меседжа')),
            ],
        ),
    ]
