# Generated by Django 3.1.6 on 2021-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.CharField(max_length=200, verbose_name='Текст меседжа'),
        ),
    ]
