# Generated by Django 3.1.7 on 2021-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210226_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cover',
            field=models.ImageField(default='covers/default.png', upload_to='covers/'),
        ),
    ]
