# Generated by Django 3.1.7 on 2021-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210321_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='cover',
            field=models.ImageField(default='covers/lector_photo/turtle.png', upload_to='covers/lector_photo'),
        ),
    ]
